### ISSUE TITLE
Code Review: sobre o funcionamento da StyleDetailViewController

### ISSUE THREAD

**Issue by gabrielsantiago4** [daneccc/brew#1]
https://github.com/daneccc/brew/blob/60353a72b9876bba6ba280c1586febe603ff73de/BrewBeer/Controllers/StyleDetailViewController.swift#L78-L81

Fala, Daniery! Eu vi que o app tá dando um problema quando se tenta navegar pra `StyleDetailViewController`, e eu acho que eu sei como resolver. O erro tá ocorrendo porque um dos componentes, o `numberLabel`, tá faltando ser adicionado como subview pra ser exibido quando a função for chamada. Eu vi que essa linha do código já tá aí, então vai ser só uma questão de "descomentar" esse trecho. Depois me avisa se deu certo!

**Comment by daneccc** [comment]
Fixed, thanks.
